contest_2_task_H
kirilliliychalgosy/algosy4sem pull request #8
Opened 2023-04-23 22:48 UTC by kirilliliychalgosy

2023-05-19 00:22 UTC, RickMortey requested changes

2023-05-19 00:22 UTC, RickMortey commented on 2contest/h.cpp
> +            std::complex<double> *fft_root_from_1_ptr = complex_roots_from_1;
ну как будто-бы для такого и структуру не грех завести

2023-05-19 00:22 UTC, RickMortey commented on 2contest/h.cpp
> +    }
std::max не используется из-за оптимизации или с какой-то другой целью?

2023-05-21 08:38 UTC, kirilliliychalgosy commented on 2contest/h.cpp
> +    }
Из-за оптимизации, да. Мб с std::max лучше читается, но уже какая-то привычка лишний раз не лезть в std, когда можно сделать ручками и будет выглядеть не слишком ужасно, тут как будто глаза не вытекают (скажи, если все-таки лучше заменить).

2023-05-22 21:45 UTC, RickMortey commented on 2contest/h.cpp
> +    }
лучше заменить, так как на ревью да и в целом читаемость > скорость выполнения чаще всего (не уходя в крайности). + на крайняк можно самому функцию max написать с шаблончиками конечно

2023-05-22 21:47 UTC, RickMortey requested changes

2023-05-22 21:47 UTC, RickMortey commented on 2contest/h.cpp
> +            context.fft_root_from_1_ptr = complex_roots_from_1;
Как будто бы хотелось вызывать один метод, по названию которого было бы понятно, что он делает и кайфовать.
Сейчас просто происходит та же ситуация, просто вместо кучи мнимых чисел теперь одна структура.

2023-05-22 21:47 UTC, RickMortey commented on 2contest/h.cpp
> +                context.ToNextData();
сейм коммент

2023-05-24 17:18 UTC, RickMortey approved these changes
Кажется, теперь намного проще стало понимать, что происходит в коде, без необходимости глубоко погружаться в структуру. Аппрувед

2023-05-24 17:18 UTC, merged